services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Client/'
            - '../src/Provider/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    guzzle_client:
        class: GuzzleHttp\Client

    api_client:
        class: App\Client\Api\Client
        arguments:
            $dsn: '%env(CUSTOMER_LIST_URL)%'
            $client: '@guzzle_client'

    App\Provider\ProviderInterface: '@api.data_provider'

    api.data_provider:
        class: App\Provider\Api\DataProvider
        arguments:
            $client: '@api_client'

    api.data_importer:
        class: App\Importer\Api\DataImporter
        arguments:
            $provider: '@api.data_provider'